"""empty message

Revision ID: 406bd87b6471
Revises: 71339530950b
Create Date: 2023-08-03 14:41:55.084095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406bd87b6471'
down_revision = '71339530950b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
